// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwkkkgnjzovywfneobil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13a2trZ25qem92eXdmbmVvYmlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0NDU4OTksImV4cCI6MjA1NDAyMTg5OX0.OdQhXAeBZORHW1LjqRhF3yGEZP1FyeYjVxfmAbRC3lw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);